### ISSUE TITLE
error on heroku app

### ISSUE THREAD

**Issue by DancinDirk** [shortstuffsushi/Universal-Link-Validator#1]
Was trying to check out how this works and am getting and error.

![screenshot 2015-09-30 17 07 40](https://cloud.githubusercontent.com/assets/414755/10206628/e5093110-6795-11e5-9f90-c6752f551621.png)

**Comment by shortstuffsushi** [comment]
Yep, noticed (/caused :wink:) earlier by another user. Should be back online now, and a fix to prevent the crash is in the works.

**Comment by DancinDirk** [comment]
It was back on for a minute, but now it's back down.

**Comment by shortstuffsushi** [comment]
Give it a shot now. I just pushed the updates that should fix the issue that was causing the crash, and make submitting an app a bit nicer.

**Comment by shortstuffsushi** [comment]
Can see you hitting it in real time :) Looks like it's working for you.

**Comment by DancinDirk** [comment]
it works! and I actually got a valid file this time!

Is the IPA uploader not working?

**Comment by shortstuffsushi** [comment]
As far as I can tell, it is working, just very slowly (this will probably vary depending on upload size). Keep in mind this is running on a free dyno on Heroku. I'll probably migrate it soon enough, as I only ever put it on there to test the deployment process on Heroku.

**Comment by DancinDirk** [comment]
Question, have you ever had a file that validates but still doesn't open the app? It's driving me crazy trying to figure it out.

**Comment by shortstuffsushi** [comment]
Yeah, definitely. This isn't the "end all" solution -- this is just some of the common issues. However, based on what I saw when I scraped your site locally, I think you may be using the wrong JSON format. I just yesterday published a bug w/ Apple, since their docs are now listing a different format than what was originally given. You're using

```
{
    "applinks": {
        "apps": [],
        "details": [
            {
                "appID": "...",
                "paths": [ "..." ]
            }
        ]
    }
}
```

while the previous version (the one I've had success with) looks like

```
{
    "applinks": {
        "apps": [],
        "details": {
            "{{app-identifier}}": {
                "paths": [ "..." ]
            }
       }
   }
}
```

Note, I could be wrong here, as what you're using _is_ in the official Apple docs now, it's just not what they had presented earlier (at WWDC). You can see that most services that are hosting this file use the older format, though (see bnc.lt, twitter.com, etc).

**Comment by DancinDirk** [comment]
Tried changing to that format, still validates, still does not open the app

**Comment by shortstuffsushi** [comment]
If you check your device console (not Xcode console, device console), you may be able to see it pinging your server and the associated error code. Note, this only happens after you first install on the device.

**Comment by DancinDirk** [comment]
I've tried looking at device console but don't see it in there, tried searching for all the common ideas, like apple-app-site-association (note even the word association doesn't appear in the console). any hints what to search for in the console?

I have deleted and re-ran the app multiple times. In the early stages of launching the app I do see (by way of a web debugger/proxy) calls being made to my domain (but they're encrypted so I can't see anything other than that they are response 200.

**Comment by shortstuffsushi** [comment]
Hi @DancinDirk -- sorry for the delay in response. Without seeing your project, it's difficult for me to guess what else may be wrong. Would you be interested in spending some actual screensharing time together or something? If so, shoot me an email directly (contact in profile) and we can get something set up. I know this is a huge pain, but perhaps I can use whatever we find to further this project!
